version: '3.8'

services:
  logger1:
    image: alpine:latest
    container_name: logger1
    command: >
      sh -c '
      while true; do
        echo "[$$(date +%Y-%m-%d\ %H:%M:%S)] Container1: $$(openssl rand -hex 8)"
        sleep 1
      done'
    restart: unless-stopped

  logger2:
    image: alpine:latest
    container_name: logger2
    command: >
      sh -c '
      while true; do
        echo "[$$(date +%Y-%m-%d\ %H:%M:%S)] Container2: $$(openssl rand -hex 8)"
        sleep 1
      done'
    restart: unless-stopped